apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "person-master.mysqlName" . }}
  labels:
    {{- include "person-master.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  serviceName: {{ include "person-master.mysqlName" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "person-master.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "person-master.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.service.port }}
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          {{- include "person-master.labels" . | nindent 10 }}
          app.kubernetes.io/component: mysql
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.mysql.storage.storageClass }}
        storageClassName: {{ .Values.mysql.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.storage.size }}
